config/routes.rb
Rails.application.routes.draw do
  resources :versions
  devise_for :users
  resources :clients
  resources :manufacturers
  resources :prducts
  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "projects#index"

  get '/archive' => "projects#archive"
  get '/projects/:id/archive' => 'projects#archiving', as: :archive_project
  get '/projects/:id/unarchive' => 'projects#unarchiving', as: :unarchive_project
  
end

app/models/prduct.rb
class Prduct < ApplicationRecord
    belongs_to :manufacturer
    has_and_belongs_to_many :projects
    has_many :versions
end

app/controllers/prducts_controller.rb
class PrductsController < ApplicationController
  before_action :set_prduct, only: [:show, :edit, :update, :destroy]

  # GET /prducts
  # GET /prducts.json
  def index
    @prducts = Prduct.all
  end

  # GET /prducts/1
  # GET /prducts/1.json
  def show
  end

  # GET /prducts/new
  def new
    @prduct = Prduct.new
  end

  # GET /prducts/1/edit
  def edit
  end

  # POST /prducts
  # POST /prducts.json
  def create
    @prduct = Prduct.new(prduct_params)

    respond_to do |format|
      if @prduct.save
        format.html { redirect_to @prduct, notice: 'Prduct was successfully created.' }
        format.json { render :show, status: :created, location: @prduct }
      else
        format.html { render :new }
        format.json { render json: @prduct.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prducts/1
  # PATCH/PUT /prducts/1.json
  def update
    respond_to do |format|
      if @prduct.update(prduct_params)
        format.html { redirect_to @prduct, notice: 'Prduct was successfully updated.' }
        format.json { render :show, status: :ok, location: @prduct }
      else
        format.html { render :edit }
        format.json { render json: @prduct.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prducts/1
  # DELETE /prducts/1.json
  def destroy
    @prduct.destroy
    respond_to do |format|
      format.html { redirect_to prducts_url, notice: 'Prduct was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prduct
      @prduct = Prduct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prduct_params
      params.require(:prduct).permit(:name, :product_type, :description, :manufacturer_id, :has_mib, :has_access, project_ids: [])
    end
end

app/helpers/prducts_helper.rb
module PrductsHelper
end

app/views/prducts/_form.html.erb
<div class="form">
  <%= simple_form_for @prduct do |f| %>

    <div class="row">
      <div class="col">
        <%= f.association :manufacturer, label: 'Manufacturer', input_html: { class: 'dropdown' } %>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <%= f.input :name, include_blank: false%>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <%= f.input :product_type, label: "Type d'équipement", placeholder: "Émetteur TV" %>
      </div>
      <div class="col">
        <%= f.input :has_mib, label: "MIB fournie" %>
        <%= f.input :has_access, label: "Accès fournie", input_html: { onchange: 'myFunction()', id: 'access' } %>
      </div>
    </div>

    <%= f.input :description, label: "Description du produit" %>  

    <div class="footer-buttons">
      <%= f.button :submit, class: "validate btn", value: "AJOUTER" %>
      <%= link_to 'ANNULER', projects_path, class: "cancel btn" %>
    </div>
  <% end %>
</div>

app/views/prducts/edit.html.erb
<h1>Editing Prduct</h1>

<%= render 'form', prduct: @prduct %>

<%= link_to 'Show', @prduct %> |
<%= link_to 'Back', prducts_path %>

app/views/prducts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prducts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prducts.each do |prduct| %>
      <tr>
        <td><%= prduct.name %></td>
        <td><%= prduct.product_type %></td>
        <td><%= prduct.description %></td>
        <td><%= link_to 'Show', prduct %></td>
        <td><%= link_to 'Edit', edit_prduct_path(prduct) %></td>
        <td><%= link_to 'Destroy', prduct, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prduct', new_prduct_path %>

app/views/prducts/new.html.erb
<%= render 'form', prduct: @prduct %>

app/views/prducts/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @prduct.name %></h1>

<div class="links">
  <%= link_to image_tag("edit.png"), edit_project_path(@prduct) %>  |
  <% if user_signed_in? && current_user.admin? %>
    <%= link_to image_tag("delete.png"), @prduct, :method => :delete, confirm: "Are you sure?" %>
  <% end %>
</div>

<div class="show">
  <div class="row">
    <div class="col">
      <div class="row">
        <div class="col">
          <%= image_tag("manufacturer.png") %>
        </div>
        <div class="col text">
          <%= @prduct.manufacturer.name %>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="row">
        <div class="col">
          <%= image_tag("type.png") %>
        </div>
        <div class="col text">
          <%= @prduct.product_type %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= @prduct.description %>
    </div>
  </div>

  <div class="row">
    <table class="table col-md-6 offset-md-3">
      <thead class="thead-dark">
        <tr>
          <th scope="col">WCM cible</th>
          <th scope="col">Configfile Version</th>
          <th scope="col">Format</th>
          <th scope="col">Status</th>
        </tr>
      </thead>

      <tbody>
        <% @prduct.versions.each do |version| %>
          <tr>
            <td><%= version.wcm %></td>
            <td><%= version.configfile %></td>
            <td><%= version.format %></td>
            <td><%= version.status %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <%= link_to 'Create new version', new_version_path, class: "btn btn-info" %>

  <div class="row">
    <div class="col-md-6 offset-md-3 driver-list">
      <div class="row">
        <%= image_tag("project.png") %><b><p>Utilisé par :</p></b>
      </div>
      <div>
        <ul>
          <% @prduct.projects.each do |project| %>
            <%= link_to project_path(project) do %>
              <li><%= project.client.name %></li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>