config/routes.rb
Rails.application.routes.draw do
  resources :versions
  devise_for :users
  resources :clients
  resources :manufacturers
  resources :prducts
  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "projects#index"

  get '/archive' => "projects#archive"
  get '/projects/:id/archive' => 'projects#archiving', as: :archive_project
  get '/projects/:id/unarchive' => 'projects#unarchiving', as: :unarchive_project
  
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :client
    has_and_belongs_to_many :users
    has_and_belongs_to_many :prducts

    enum priority: { low: 0, medium: 50, high: 100 }
    enum project_type: { poc: 0, pilote: 50, win: 100 }
    enum licence_type: { WCM25: 25, WCM50: 50, WCM100: 100, WCM250: 250, WCM500: 500, WCM1000: 1000 }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.where(is_archive: false).order(priority: :desc)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  def archive
    @projects = Project.where(is_archive: true).order(updated_at: :desc)
  end

  def archiving
    unless current_user.admin?
        redirect_to root_path, notice: 'Vous devez être administrateur'
    end

    @projects = Project.find(params[:id])
    @projects.is_archive = true
    @projects.save
    redirect_to :action => 'archive'
  end

  def unarchiving
    unless current_user.admin?
        redirect_to root_path, notice: 'Vous devez être administrateur'
    end

    @projects = Project.find(params[:id])
    @projects.is_archive = false
    @projects.save
    redirect_to :action => 'index'
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to action: "index" }
        format.json { render :index, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :location, :siteNumber, :description, :unitNumber, :project_type, :installed, :installation_date, :licence_type, :licence_date_start, :licence_date_end, :client_id, :priority, user_ids: [], prduct_ids: [])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<div class="form">
  <%= simple_form_for @project do |f| %>

    <div class="row">
      <div class="col">
        <%= f.association :client, label: 'Client', input_html: { class: 'dropdown' } %>
        <%= link_to 'Create client', new_client_path %>
      </div>
      <div class="col">
        <%= f.input :priority, include_blank: false%>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <%= image_tag("placeholder.png") %><%= f.input :siteNumber, label: 'Nombre de site' %>
      </div>
      <div class="col">
        <%= image_tag("server.png") %><%= f.input :unitNumber, label: "Nombre d'équipement" %>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <%= image_tag("business.png") %><%= f.association :users, collection: User.business, as: :check_boxes, label_method: :email, label: 'Commerciaux' %>
      </div>
      <div class="col">
        <%= image_tag("support.png") %><%= f.association :users, collection: User.support, as: :check_boxes, label_method: :email, label: 'Support' %>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <%= image_tag("presentation.png") %><%= f.input :project_type %>
      </div>
      <div class="col">
        <div class="row">
          <div class="col">
            <%= f.input :installed, label: "Installtion faite ?", input_html: { onchange: 'enable_disable_licence()', id: 'licence' } %>
          </div>
          <div class="col">
            <%= f.input :installation_date, label: "Date de l'installation", input_html: { disabled: true} %>
          </div>
        </div>
        <div class="row">
          <div class=col>
            <%= f.input :licence_type, label: "Taille de la licence", input_html: { id: 'licence_type', disabled: true} %>
          </div>
          <div class=col>
            <%= f.input :licence_date_start, label: "Début de la licence", input_html: { disabled: true} %>
          </div>
          <div class=col>
            <%= f.input :licence_date_end, label: "Fin de la licence", input_html: { disabled: true} %>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <%= f.input :description, label: "Description du projet" %>
      </div>
    </div> 

    <div class="row">
      <div class="col-md-6 offset-md-3">
        <%= image_tag("teamviewer.png") %><%= f.input :has_teamviewer, label: "Accès TeamViewer ?", input_html: { onchange: 'enable_disable_teamviewer()', id: 'teamviewer' } %>
        <div class="row">
          <div class="col">
            <%= f.input :teamviewer_login, label: "Login", input_html: { id: 'teamviewer_login', disabled: true} %>
          </div>
          <div class="col">
            <%= f.input :teamviewer_pass, label: "Password", input_html: { id: 'teamviewer_pass', disabled: true} %>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <%= f.association :prducts, label: 'Drivers', input_html: { class: 'dropdown', multiple:'multiple' } %>
        <%= link_to 'Create product', new_prduct_path %>
      </div>
      <div class="col">
        
      </div>
    </div> 

    <div class="footer-buttons">
      <%= f.button :submit, class: "validate btn", value: "AJOUTER" %>
      <%= link_to 'ANNULER', projects_path, class: "cancel btn" %>
    </div>
  <% end %>
</div>

app/views/projects/archive.html.erb
<div class="row justify-content-md-center">
  <% @projects.each do |project| %>
    <div class="col-sm-3 card">
      <%= link_to project_path(project) do %>
        <div class="row align-items-start">
          <div class="col">
            <div class="priority">
              <%= project.priority %>
            </div>
          </div>
          <div class="col">
            <div class="name">
              <h4><%= project.client.name %></h4>
            </div>
            <div class="location">
              <% if project.client.location != nil %>
                <%= image_tag("pin.png")%><%= project.client.location %>
              <% end %>
            </div>
          </div>
          <div class="col">
          </div>
        </div>
        <div class="row align-items-end">
          <div class="col">
            <div class="units">
              <% if project.unitNumber != nil %>
                <%= image_tag("server.png") %><%= project.unitNumber %>
              <% else %>
                <%= image_tag("server.png") %><p>TBD</p>
              <% end %>
            </div>
          </div>
          <div class="col">
          </div>
          <div class="col">
            <div class="site">
              <% if project.unitNumber != nil %>
                <%= image_tag("placeholder.png") %><%= project.siteNumber %>
              <% else %>
                <%= image_tag("server.png") %><p>TBD</p>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<%= link_to 'New Project', new_project_path, class: "btn btn-primary btn-lg main-btn"%>
<%= link_to 'Create Client', new_client_path, id: 'createClient' %>

<div class="row justify-content-md-center">
  <% @projects.each do |project| %>
    <%# <% if project.is_admin != true %>
      <div class="col-sm-3 card">
        <%= link_to project_path(project) do %>
          <div class="row align-items-start">
            <div class="col">
              <div class="priority">
                <%= project.priority %>
              </div>
            </div>
            <div class="col">
              <div class="name">
                <h4><%= project.client.name %></h4>
              </div>
              <div class="location">
                <% if project.client.location != nil %>
                  <%= image_tag("pin.png")%><%= project.client.location %>
                <% end %>
              </div>
            </div>
            <div class="col">
            </div>
          </div>
          <div class="row align-items-end">
            <div class="col">
              <div class="units">
                <% if project.unitNumber != nil %>
                  <%= image_tag("server.png") %><%= project.unitNumber %>
                <% else %>
                  <%= image_tag("server.png") %><p>TBD</p>
                <% end %>
              </div>
            </div>
            <div class="col">
            </div>
            <div class="col">
              <div class="site">
                <% if project.unitNumber != nil %>
                  <%= image_tag("placeholder.png") %><%= project.siteNumber %>
                <% else %>
                  <%= image_tag("server.png") %><p>TBD</p>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <%# <% end %>
  <% end %>
</div>

app/views/projects/new.html.erb
<%= render 'form', project: @project %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @project.client.name %></h1>

<div class="links">
  <%= link_to image_tag("edit.png"), edit_project_path(@project) %>  |
  <% if user_signed_in? && current_user.admin? %>
    <%= link_to image_tag("delete.png"), @project, :method => :delete, confirm: "Are you sure?" %> |
    <% if @project.is_archive == false %>
      <%= link_to image_tag("archive.png"), archive_project_path(@project.id), confirm: "Are you sure?" %>
    <% else %>
      <%= link_to image_tag("archive.png"), unarchive_project_path(@project.id), confirm: "Are you sure?" %>
    <% end %>
  <% end %>
</div>

<div class="show">
  <div class="row">
    <div class="col">
      <div class="row">
        <div class="col">
          <%= image_tag("email.png") %>
        </div>
        <div class="col text">
          <%= @project.client.email %>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <%= image_tag("business.png") %>
        </div>
        <div class="col text">
          <ul>
            <% @project.users.business.each do |user| %>
              <li><%= user.email %></li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <%= image_tag("support.png") %>
        </div>
        <div class="col text">
          <ul>
            <% @project.users.support.each do |user| %>
              <li><%= user.email %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="row">
        <div class="col">
          <%= image_tag("pin.png") %>
        </div>
        <div class="col text">
          <%= @project.client.location %>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <%= image_tag("server.png") %>
        </div>
        <div class="col text">
          <%= @project.unitNumber %>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <%= image_tag("placeholder.png") %>
        </div>
        <div class="col text">
          <%= @project.siteNumber %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col description">
      <%= @project.description %>
    </div>
  </div>

  <% if @project.installed == true %>
  <hr>
  <b><p>Installation</p></b>
    <div class="row">
      <div class="col">
        <div class="row">
          <div class="col">
            <%= image_tag("install.png") %>
          </div>
          <div class="col text">
            <%= @project.installation_date.strftime("%d/%m/%Y") %>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="row">
          <div class="col">
            <%= image_tag("licensekey.png") %>
          </div>
          <div class="col text">
            <%= @project.licence_type %>
            <div class="row">
              <div class="col">
                <%= @project.licence_date_start.strftime(" Du %d/%m/%Y") %>
              </div>
              <div class="col">
                <%= @project.licence_date_end.strftime("au %d/%m/%Y") %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <hr>
  <b><p>Liste des drivers</p></b>
  <div class="row">
    <div class="col">
      <%= image_tag "driver.png", id: "driver-icon" %>
    </div>
    <table class="table col-6">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Fabricant</th>
          <th scope="col">Produit</th>
          <th scope="col">Status</th>
        </tr>
      </thead>

      <tbody>
        <% @project.prducts.each do |product| %>
          <tr>
            <td><%= product.manufacturer.name %></td>
            <%= link_to prduct_path(product) do %>
              <td><%= product.name %></td>
            <% end %>
            <td><%= product.versions.last.status %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="col">
    </div>
  </div>
</div>