config/routes.rb
Rails.application.routes.draw do
  resources :versions
  devise_for :users
  resources :clients
  resources :manufacturers
  resources :prducts
  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "projects#index"

  get '/archive' => "projects#archive"
  get '/projects/:id/archive' => 'projects#archiving', as: :archive_project
  get '/projects/:id/unarchive' => 'projects#unarchiving', as: :unarchive_project
  
end

app/models/version.rb
class Version < ApplicationRecord
    belongs_to :prduct

    enum wcm: { '3.7': 0, '3.8': 10 }
    enum status: { 'New': 0, 'In developpment': 10, 'To be tested': 20, 'Is validate': 30 }
    enum format: { Classic: 0, Javascript: 10, Typescript: 20 }
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  before_action :set_version, only: [:show, :edit, :update, :destroy]

  # GET /versions
  # GET /versions.json
  def index
    @versions = Version.all
  end

  # GET /versions/1
  # GET /versions/1.json
  def show
  end

  # GET /versions/new
  def new
    @version = Version.new
  end

  # GET /versions/1/edit
  def edit
  end

  # POST /versions
  # POST /versions.json
  def create
    @version = Version.new(version_params)

    respond_to do |format|
      if @version.save
        format.html { redirect_to @version, notice: 'Version was successfully created.' }
        format.json { render :show, status: :created, location: @version }
      else
        format.html { render :new }
        format.json { render json: @version.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /versions/1
  # PATCH/PUT /versions/1.json
  def update
    respond_to do |format|
      if @version.update(version_params)
        format.html { redirect_to @version, notice: 'Version was successfully updated.' }
        format.json { render :show, status: :ok, location: @version }
      else
        format.html { render :edit }
        format.json { render json: @version.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /versions/1
  # DELETE /versions/1.json
  def destroy
    @version.destroy
    respond_to do |format|
      format.html { redirect_to versions_url, notice: 'Version was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_version
      @version = Version.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def version_params
      params.require(:version).permit(:wcm, :configfile, :prduct_id, :format, :status)
    end
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/versions/_form.html.erb
<div class="form">
  <%= simple_form_for @version do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="row">
      <div class="col">
        <%= f.association :prduct, label: 'Products', input_html: { class: 'dropdown' } %>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <%= f.input :wcm, label: 'Version WCM cible' %>
      </div>
      <div class="col">
        <%= f.input :configfile, label: 'Configfile version' %>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <%= f.input :format, include_blank: false, label: "Format"%>
      </div>
      <div class="col">
        <%= f.input :status, include_blank: false, label: "Status"%>
      </div>
    </div>

    <div class="footer-buttons">
      <%= f.button :submit, class: "validate btn", value: "AJOUTER" %>
      <%= link_to 'ANNULER', projects_path, class: "cancel btn" %>
    </div>
<% end %>
</div>

app/views/versions/edit.html.erb
<h1>Editing Version</h1>

<%= render 'form', version: @version %>

<%= link_to 'Show', @version %> |
<%= link_to 'Back', versions_path %>

app/views/versions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Versions</h1>

<table>
  <thead>
    <tr>
      <th>Wcm</th>
      <th>Configfile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @versions.each do |version| %>
      <tr>
        <td><%= version.wcm %></td>
        <td><%= version.configfile %></td>
        <td><%= link_to 'Show', version %></td>
        <td><%= link_to 'Edit', edit_version_path(version) %></td>
        <td><%= link_to 'Destroy', version, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Version', new_version_path %>

app/views/versions/new.html.erb
<h1>Nouvelle version</h1>

<%= render 'form', version: @version %>

app/views/versions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Wcm:</strong>
  <%= @version.wcm %>
</p>

<p>
  <strong>Configfile:</strong>
  <%= @version.configfile %>
</p>

<%= link_to 'Edit', edit_version_path(@version) %> |
<%= link_to 'Back', versions_path %>