config/routes.rb
Rails.application.routes.draw do
  resources :versions
  devise_for :users
  resources :clients
  resources :manufacturers
  resources :prducts
  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "projects#index"

  get '/archive' => "projects#archive"
  get '/projects/:id/archive' => 'projects#archiving', as: :archive_project
  get '/projects/:id/unarchive' => 'projects#unarchiving', as: :unarchive_project
  
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
    has_many :prducts
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  before_action :set_manufacturer, only: [:show, :edit, :update, :destroy]

  # GET /manufacturers
  # GET /manufacturers.json
  def index
    @manufacturers = Manufacturer.order(:name)
  end

  # GET /manufacturers/1
  # GET /manufacturers/1.json
  def show
  end

  # GET /manufacturers/new
  def new
    @manufacturer = Manufacturer.new
  end

  # GET /manufacturers/1/edit
  def edit
  end

  # POST /manufacturers
  # POST /manufacturers.json
  def create
    @manufacturer = Manufacturer.new(manufacturer_params)

    respond_to do |format|
      if @manufacturer.save
        format.html { redirect_to @manufacturer, notice: 'Manufacturer was successfully created.' }
        format.json { render :show, status: :created, location: @manufacturer }
      else
        format.html { render :new }
        format.json { render json: @manufacturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manufacturers/1
  # PATCH/PUT /manufacturers/1.json
  def update
    respond_to do |format|
      if @manufacturer.update(manufacturer_params)
        format.html { redirect_to @manufacturer, notice: 'Manufacturer was successfully updated.' }
        format.json { render :show, status: :ok, location: @manufacturer }
      else
        format.html { render :edit }
        format.json { render json: @manufacturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manufacturers/1
  # DELETE /manufacturers/1.json
  def destroy
    @manufacturer.destroy
    respond_to do |format|
      format.html { redirect_to manufacturers_url, notice: 'Manufacturer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manufacturer
      @manufacturer = Manufacturer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manufacturer_params
      params.require(:manufacturer).permit(:name, :website)
    end
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/views/manufacturers/_form.html.erb
<div class="form">
  <%= simple_form_for @manufacturer do |f| %>
    <div class="row">
      <div class="col">
        <%= f.input :name, include_blank: false %>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <%= f.input :website %>
      </div>
    </div>

    <div class="footer-buttons">
      <%= f.button :submit, class: "validate btn", value: "AJOUTER" %>
      <%= link_to 'ANNULER', projects_path, class: "cancel btn" %>
    </div>
  <% end %>
</div>

app/views/manufacturers/edit.html.erb
<h1>Editing Manufacturer</h1>

<%= render 'form', manufacturer: @manufacturer %>

<%= link_to 'Show', @manufacturer %> |
<%= link_to 'Back', manufacturers_path %>

app/views/manufacturers/index.html.erb
<%= link_to 'New Manufacturer', new_manufacturer_path, class: "btn btn-primary btn-lg main-btn"%>


<div class="row justify-content-md-center">
  <% @manufacturers.each do |manufacturer| %>
      <div class="col-sm-3 card">
        <%= link_to manufacturer_path(manufacturer) do %>
          <div class="manufacturer-name">
            <%= manufacturer.name %>
          </div>
        <% end %>
      </div>
  <% end %>
</div>

app/views/manufacturers/new.html.erb
<h1>New Manufacturer</h1>

<%= render 'form', manufacturer: @manufacturer %>

app/views/manufacturers/show.html.erb
<h1><%= @manufacturer.name %></h1>
<p><%= link_to @manufacturer.website %></p>

<%= link_to 'New Product', new_prduct_path, class: "btn btn-primary btn-lg main-btn"%>

<div class="row justify-content-md-center">
  <% @manufacturer.prducts.each do |product| %>
      <div class="col-sm-3 card">
        <%= link_to prduct_path(product) do %>
          <div class="product-name">
            <%= product.name %>
          </div>
        <% end %>
      </div>
  <% end %>
</div>